version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run app.py
    environment:
      - STREAMLIT_SERVER_PORT=8501
