name: Schedule Python Job

on:
  schedule:
    - cron: '00 00 * * *'

jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Python script
      run: python Miscellaneous/metadataScrapper.py
